# Generated by Django 3.1 on 2022-06-24 06:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NewsArticles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[(None, '--- Select Type ---'), ('breaking', 'Breaking News'), ('innovation', 'Innovation'), ('discovery', 'Discovery'), ('methods', 'Methods'), ('research', 'Research Articles'), ('news', 'News'), ('history', 'History'), ('story', 'Story')], max_length=20, null=True)),
                ('headline', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('img', models.ImageField(upload_to='', verbose_name='Article Image')),
                ('pub_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('mod_date', models.DateTimeField(auto_now=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
